import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// The children is each page in next.js
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      {/* to avoid warning from grammarly  */}
      <body suppressHydrationWarning={true}>
        <div className="page-container">
          {children}
        </div>
      </body>
    </html>
  )
}
